services:
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: dbeaver_cloudbeaver
    restart: unless-stopped
    ports:
      - "8978:8978"
    volumes:
      - cloudbeaver_workspace:/opt/cloudbeaver/workspace
    networks:
      - proxy_network
    environment:
      - CLOUDBEAVER_FORCE_HTTPS=false
